server:
  port: 8002

spring:
  application:
    name: EDU-VIDEO
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 47.117.112.24
    port: 6379

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8888/eureka/

oss:
  accessKeyId:
  accessKeySecret:
