mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/atguigu/edu/mapper/xml/*.xml
server:
  port: 8000
spring:
  application:
    name: EDU-SERVICE
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/online_edu?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    appname: EDU-SERVICE
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000